### ISSUE TITLE
NoSuchElementException on fetching all offers from JJIT

### ISSUE THREAD

**Issue by RobertCzaja** [RobertCzaja/it-offers-api#70]
```
024-12-23 12:59:13,129 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: php
2024-12-23 12:59:18,869 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: java
2024-12-23 12:59:23,715 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: javascript
2024-12-23 12:59:27,769 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: net
2024-12-23 12:59:32,292 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: devops
2024-12-23 12:59:37,025 INFO  [main] p.a.i.p.j.s.FetchJustJoinItOffersService: [just-join-it] fetching offers from technology: go
java.util.NoSuchElementException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```

```
java.util.NoSuchElementException: null
	at java.base/java.util.Collections$EmptyIterator.next(Collections.java:4310)
	at pl.api.itoffers.provider.justjoinit.service.extractor.v2.PayloadFromJsonExtractor.extractPayload(PayloadFromJsonExtractor.java:33)
	at pl.api.itoffers.provider.justjoinit.service.extractor.v2.JustJoinItOffersFetcherV2.fetch(JustJoinItOffersFetcherV2.java:31)
	at pl.api.itoffers.provider.justjoinit.JustJoinItProvider.fetch(JustJoinItProvider.java:23)
	at pl.api.itoffers.provider.justjoinit.service.FetchJustJoinItOffersService.fetch(FetchJustJoinItOffersService.java:35)
	at pl.api.itoffers.provider.justjoinit.ui.cli.FetchOffersCommand.fetchJustJoinIt(FetchOffersCommand.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:230)
	at org.springframework.shell.Shell.evaluate(Shell.java:248)
	at org.springframework.shell.Shell.run(Shell.java:159)
	at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:72)
	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:66)
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:786)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at pl.api.itoffers.Application.main(Application.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
```

**Comment by RobertCzaja** [comment]
[CW](https://eu-north-1.console.aws.amazon.com/cloudwatch/home?region=eu-north-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-12-30T10*3a00*3a00.000Z~start~'2024-12-30T09*3a00*3a00.000Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2010000~queryId~'e5f084c8-2c18-4d6b-a1e1-773d189eb8f4~source~(~'it-offers-prod-group)))

**Comment by RobertCzaja** [comment]
Fix applied, let to make a couple of fetching in the next few days to check if everything works as expected
